Prefer type fest
Expensify/eslint-config-expensify pull request #100
Opened 2024-06-06 16:09 UTC by blazejkustra

2024-06-07 18:05 UTC, roryabraham requested changes
@blazejkustra can you add a test case when something else is imported from `type-fest`?

input:

```ts
import {RequireAtLeastOne} from 'type-fest';
const COLORS = { GREEN: 'green', BLUE: 'blue' } as const;
type Bad = (typeof COLORS)[keyof COLORS];
```

output:

```ts
// Note: ValueOf is added to an existing import
import {RequireAtLeastOne, ValueOf} from 'type-fest';
const COLORS = { GREEN: 'green', BLUE: 'blue' } as const;
type Bad = ValueOf<typeof COLORS>;
```

2024-06-10 08:51 UTC, fabioh8010 reviewed
minor comments

2024-06-10 08:51 UTC, fabioh8010 commented on eslint-plugin-expensify/CONST.js
> +        PREFER_TYPE_FEST_TUPLE_TO_UNION: 'Prefer using TupleToUnion from type-fest for converting tuple types to union types.',
```suggestion
        PREFER_TYPE_FEST_TUPLE_TO_UNION: 'Prefer using `TupleToUnion` from `type-fest` for converting tuple types to union types.',
```

2024-06-10 08:51 UTC, fabioh8010 commented on eslint-plugin-expensify/CONST.js
> +        PREFER_TYPE_FEST_VALUE_OF: 'Prefer using ValueOf from type-fest to extract the type of the properties of an object.',
```suggestion
        PREFER_TYPE_FEST_VALUE_OF: 'Prefer using `ValueOf` from `type-fest` to extract the type of the properties of an object.',
```

2024-06-10 08:51 UTC, fabioh8010 commented on eslint-plugin-expensify/prefer-type-fest.js
> +                        )
Maybe you could extract this into a separate function (addImport), so can be used in the other use case and more in the future if we have anothers?

2024-06-10 13:44 UTC, blazejkustra commented
@roryabraham & @fabioh8010 Adjusted the code after your suggestions, now all import patterns are covered 👍

2024-06-10 13:47 UTC, fabioh8010 approved these changes
minor comment, LGTM!

2024-06-10 13:47 UTC, fabioh8010 commented on eslint-plugin-expensify/utils/imports.js
> +      if(!alreadyImported) {
```suggestion
      if (!alreadyImported) {
```

2024-06-10 15:54 UTC, roryabraham approved these changes

2024-06-10 18:26 UTC, merged