Use at() instead of direct access
Expensify/eslint-config-expensify pull request #104
Opened 2024-07-03 20:19 UTC by ShridharGoel

https://github.com/Expensify/App/issues/43055

2024-07-05 16:29 UTC, eh2077 commented on eslint-plugin-expensify/tests/prefer-at.test.js
> +            code: 'example[0]',
I think we can add more tests here, like
```
array[array.length - 1];
array[0][array[0].length - 1];
array[(array.length - 1) / 2];
```

Let me try it in codebase and feedback later.

2024-07-05 16:29 UTC, eh2077 commented on eslint-plugin-expensify/prefer-at.js
> +                if (node.object.type === 'Identifier' && node.property.type === 'Literal' && typeof node.property.value === 'number') {
`node.property` is the indexNode right? If so, for expression `arr[arr.length - 1]`, then `node.property.type` shouldn't be `Literal`. Can we detect error for `arr[arr.length - 1]`?

2024-07-09 16:29 UTC, fabioh8010 commented on eslint-plugin-expensify/prefer-at.js
> +        }
Why do we need this?

2024-07-09 16:30 UTC, fabioh8010 commented on eslint-plugin-expensify/prefer-at.js
> +                }
These kind of conditions are very specific and will fail if we test with anything that is different from them.. we should either think in a condition that can capture anything inside `[...]` and convert it to `.at(...)`, **if the variable is an array**.

2024-07-09 16:36 UTC, fabioh8010 commented on eslint-plugin-expensify/tests/prefer-at.test.js
> +        },
```suggestion
        },
        {
            code: `
                const object = {0: 'v0', 1: 'v1', 2: 'v2'};
                object[0]
                `,
        },
        {
            code: '[0, 1, 2].at(1)',
        },
```

We must assert his rule will be only applied to arrays, not objects

2024-07-09 16:37 UTC, fabioh8010 commented on eslint-plugin-expensify/tests/prefer-at.test.js
> +    invalid: [
For each invalid test case here, we must assert we are dealing with arrays and not objects

2024-07-09 16:38 UTC, fabioh8010 commented on eslint-plugin-expensify/tests/prefer-at.test.js
> +        },{
```suggestion
        {
            code: `
                const sample = [];
                sample[sample.length-1]
                `,
            output: 'sample.at(sample.length-1)',
            errors: [{
                message,
            }],
        },
        {
```

For example

2024-07-09 16:38 UTC, fabioh8010 commented on eslint-plugin-expensify/tests/prefer-at.test.js
> +        },
```suggestion
        },
        {
            code: '[0, 1, 2][1]',
            output: '[0, 1, 2].at(1)',
            errors: [{
                message,
            }],
        },
```

2024-07-10 15:29 UTC, fabioh8010 commented
@ShridharGoel you must upgrade `jest` to fix this:

> Tests in the repo are failing. One is related to tests/use-periods-error-messages.test.js file (which I think we don't need to fix right now), and for the other one we need to upgrade jest to latest version (29.7.0) in order to fix it, we could do in this PR.

2024-07-15 15:52 UTC, fabioh8010 commented
@ShridharGoel 

- Add `@typescript-eslint/rule-tester` dependency to project.
- Place the `tsconfig.json` file under `eslint-plugin-expensify/tests/` folder.
- Create a empty `file.ts` file insider `eslint-plugin-expensify/tests/` folder – it's necessary for testing TS.
- Adjust the test code like this:
   ```js
   const RuleTester = require('@typescript-eslint/rule-tester').RuleTester;
   const rule = require('../prefer-at');
   const message = require('../CONST').MESSAGE.PREFER_AT;
   
   const ruleTester = new RuleTester({
       parser: '@typescript-eslint/parser',
       parserOptions: {
           project: './tsconfig.json',
           tsconfigRootDir: __dirname,
           sourceType: 'module',
           ecmaVersion: 2020,
       },
   });

   ...
   ```

Please let me know if it works or not.

2024-07-17 07:30 UTC, fabioh8010 commented
@ShridharGoel I don't understand your comment, please provide more information about the error:

- Where it happens?
- When it happens?
- Do you mind sharing your changes in a diff so I can assist you better?

2024-07-17 18:23 UTC, fabioh8010 commented
Thanks @ShridharGoel , will take a look tomorrow!

2024-07-18 09:46 UTC, fabioh8010 commented
@ShridharGoel I checked your PR and as I said before you need to upgrade `jest` in order to fix the errors when running the tests, you can upgrade by running this command `npm install jest@latest`. Please upgrade and let me know if it works.

2024-07-22 10:15 UTC, fabioh8010 reviewed
Looking good, left few comments!

2024-07-22 10:15 UTC, fabioh8010 commented on eslint-plugin-expensify/tests/prefer-at.test.js
> +        },
```suggestion
        },
        {
            code: `
                const index = 1;
                const object = {0: 'v0', 1: 'v1', 2: 'v2'};
                object[index]
                `,
        },
```

Could we add this test case too?

2024-07-22 10:15 UTC, fabioh8010 commented on eslint-plugin-expensify/tests/prefer-at.test.js
> +        },
```suggestion
        },
        {
            code: 'const index = -1; const a = [1, 2, 3, 4]; a[index]',
            output: 'const index = -1; const a = [1, 2, 3, 4]; a.at(index)',
            errors: [{
                message,
            }],
        },
```

The test will fail if we add this test case, could you check?

2024-07-22 10:15 UTC, fabioh8010 commented on eslint-plugin-expensify/prefer-at.js
> +                }
Is possible to make this code more generic to actually capture anything inside `[...]` and replace with `.at(...)` if applicable? So in this way we don't have to rely in super-specific use cases like these ones and we instead will cover all possibilities.

2024-07-24 09:59 UTC, fabioh8010 reviewed
My final comments I believe, looks really great now 🚀 Please remove the additional files and I will approve

2024-07-24 09:59 UTC, fabioh8010 commented on eslint-plugin-expensify/prefer-at.js
> +                    }
```suggestion
                    context.report({
                        node,
                        message,
                        fix(fixer) {
                            const objectText = getSourceCode(node.object);
                            return fixer.replaceText(node, `${objectText}.at(${getExpressionWithUpdatedBrackets(indexExpression)})`);
                        },
                    });
```

Do you think we really need this `a[a.length - 1]` to `a.at(-1)` use case? Seems overly specific to me and not too beneficial, it's a optimisation that the developer can apply by itself. Also, it's currently converting this wrong use case:

```ts
        {
            code: `
                const sample = [1, 2, 3, 4];
                sample[a.length - 1] // Notice that i'm using a different variable "randomVar".
                `,
            output: `
                const sample = [1, 2, 3, 4];
                sample.at(-1)
                `,
            errors: [{
                message,
            }],
        },
```

2024-07-24 09:59 UTC, fabioh8010 commented on eslint-plugin-expensify/tests/prefer-at.test.js
> +                sample.at(-1)
```suggestion
                sample.at(sample.length - 1)
```

In case you agree with my previous comment

2024-07-24 09:59 UTC, fabioh8010 commented on eslint-plugin-expensify/tests/prefer-at.test.js
> +                sample[sample.length-1]
```suggestion
                sample[sample.length - 1]
```

2024-07-24 09:59 UTC, fabioh8010 commented on eslint-plugin-expensify/tests/prefer-at.test.js
> +            output: 'const a = [1, 2, 3, 4]; a.at(-1)',
```suggestion
            output: 'const a = [1, 2, 3, 4]; a.at(a.length - 1)',
```

Same

2024-07-25 08:19 UTC, fabioh8010 approved these changes
two minor comments, besides that LGTM 🚀

2024-07-25 08:19 UTC, fabioh8010 commented on eslint-plugin-expensify/prefer-at.js
> +        }
I think this function is not being used, let's remove it?

2024-07-25 08:19 UTC, fabioh8010 commented on eslint-plugin-expensify/prefer-at.js
> +        }
Same, let's remove it?

2024-07-25 09:50 UTC, eh2077 commented
I'll take a look and test it soon

2024-07-25 14:23 UTC, fabioh8010 approved these changes

2024-07-27 16:53 UTC, roryabraham reviewed
do you think we could also verify that this case with `as const` is considered valid?

```ts
const myArr = ['a', 'b', 'c'] as const;
myArr[0]; // good, type should be `a`
myArr[1]; // good, type should be `b`
myArr[2]; // good, type should be `c`
myArr[3]; // error
```

2024-07-27 16:53 UTC, roryabraham commented on eslint-plugin-expensify/tests/file.ts
need to remove this empty file

2024-07-29 10:32 UTC, fabioh8010 commented on eslint-plugin-expensify/tests/file.ts
@roryabraham We need this file when using the `@typescript-eslint/rule-tester` package, see -> https://typescript-eslint.io/developers/custom-rules#testing-typed-rules

2024-07-30 15:31 UTC, roryabraham commented
> This would be invalid, since [] is used instead of at. Isn't it?

Right, but if you did this:

```ts
const myArr = ['a', 'b', 'c'] as const;

// This will be `'a' | 'b' | 'c' | undefined`
myArr.at(0);
```

but because this is an array defined with `as const`, it's final shape is known at compile time. So invalid access is not possible:

```
// 'a'
myArr[0];

// TS error: Tuple type readonly [1, 2, 3] of length 3 has no element at index 3
myArr[3];
```

So I'm saying we should make an exception to the rule that requires `.at()` for readonly tuple types (aka array as const)

2024-07-31 13:00 UTC, eh2077 commented on eslint-plugin-expensify/prefer-at.js
> +const ts = require('typescript');
This is never read right? If so, then I think we should remove it

2024-07-31 20:01 UTC, roryabraham approved these changes

2024-07-31 20:02 UTC, roryabraham commented
@ShridharGoel heads-up that I am unable to merge this because it contains unsigned commits

2024-07-31 20:29 UTC, roryabraham requested changes
can you please add `.idea` to the gitignore?

2024-07-31 21:19 UTC, roryabraham approved these changes

2024-07-31 21:19 UTC, merged

2024-08-06 14:50 UTC, carlosmiceli commented
@ShridharGoel @roryabraham question: we've been trying with @MonilBhavsar to bump the eslint version in the App but we've been getting [this](https://github.com/Expensify/App/actions/runs/10223112808/job/28288921682?pr=46625) error, which seems to be related to this rule added here? Any advice on how we should proceed?

2024-08-06 16:50 UTC, carlosmiceli commented
Got it, would you please let me know when it's ready? thank you!

2024-08-09 18:11 UTC, carlosmiceli commented
@ShridharGoel small bump :)

2024-08-09 21:54 UTC, carlosmiceli commented
@ShridharGoel Merged, thank you! Question though, do you know why [this](https://github.com/Expensify/App/pull/44651/files) may be failing still with these period rules? I can see that the rule is updated already [here](https://github.com/Expensify/eslint-config-expensify/blob/main/eslint-plugin-expensify/use-periods-for-error-messages.js) and tests as well.

2024-08-13 11:58 UTC, carlosmiceli commented
@ShridharGoel @roryabraham I see that the [version](https://github.com/Expensify/App/blob/main/package-lock.json#L220) hasn't been bumped yet and it's been over a week since [this](https://github.com/Expensify/eslint-config-expensify/pull/104#issuecomment-2271698781) comment, do we know when are we going to do this? It's holding [this PR](https://github.com/Expensify/App/pull/44651), but not sure if there's something that's holding it back that I'm unaware of 🙏