Make the 'no-use-before-define' rule a warning
Expensify/eslint-config-expensify pull request #21
Opened 2020-12-04 15:12 UTC by Julesssss

The 'no-use-before-define' rule is incorrectly flagging functions. Functions will actually be hoisted to the top of the file, so this error should be reduced to a warning. 

### Test

To verify this change in the ReactNativeChat repo:
- Locate the file `node_modules/eslint-config-expensify/rules/style.js`
- From `ReactNativeChat`, checkout this commit: `git checkout 02b01a72402eba55dd9460ea3854b02e591e7cca`
- Add this line `'no-use-before-define': 'warn',` beneath line 70
- Run `git log`, verify this is the latest commit message: ' add server Log to authToken error flow'
- Run `npm run lint`
- Check for the following **warning**

**Expected warning**
![Screenshot 2020-12-04 at 14 46 30](https://user-images.githubusercontent.com/10736861/101178959-865dcb00-3641-11eb-8705-2eee524421c1.png)

2020-12-04 16:50 UTC, marcaaron requested changes
I think this _should_ remain an error? Left some thoughts in the thread [here](https://expensify.slack.com/archives/C03TQ48KC/p1607100069369300?thread_ts=1607018465.328700&cid=C03TQ48KC)

2020-12-04 17:59 UTC, Julesssss commented
Closing in favour of obeying the lint warning, [see thread]([url](https://expensify.slack.com/archives/C03TQ48KC/p1607104588380900?thread_ts=1607018465.328700&cid=C03TQ48KC)) for further discussion

2020-12-07 12:19 UTC, Julesssss commented
Simply reordering functions was not a viable solution, due to a function dependency loop. See [[here for full information and options]](https://github.com/Expensify/ReactNativeChat/pull/889#issuecomment-739875960).

Best path forward is to ignore the lint manually or to cancel adding the log.

2020-12-16 13:43 UTC, Julesssss commented
Managed to find the offending request without needing the log after all, closing. 

[Created this issue](https://github.com/Expensify/Expensify/issues/148468) to fix the issue we were originally trying to locate.

2020-12-16 13:43 UTC, closed without merging