Justice constructors in react components should accept props
Expensify/eslint-config-expensify pull request #49
Opened 2022-03-17 08:38 UTC by Justicea83

### Fixed Issues
$https://github.com/Expensify/App/issues/7821

### Tests
1. Confirm all tests still pass

2022-03-17 11:14 UTC, Justicea83 commented
cc @madmax330

2022-03-17 11:23 UTC, Justicea83 commented
updated and waiting for another review @marcaaron

2022-03-17 17:33 UTC, marcaaron requested changes

2022-03-17 17:36 UTC, Justicea83 commented on eslint-plugin-expensify/CONST.js
> +        PREFER_REACT_CLASS_CONSTRUCTORS_WITH_PROPS: 'React class constructors must accept props.',
sure, I'll update it

2022-03-17 18:01 UTC, Justicea83 commented
> @Justicea83 What do you think about this comment [#49 (comment)](https://github.com/Expensify/eslint-config-expensify/pull/49#issuecomment-1071140100) and should we add another test case for that?

We shouldn't be able to as per the rules in the GH

2022-03-17 18:05 UTC, roryabraham commented
@marcaaron [this example](https://github.com/Expensify/App/blob/2c7c82cbe534e931b85a737a86aeb20bbef058ac/src/styles/animation/SpinningIndicatorAnimation.js#L4-L12) does not extend the `React.Component` class, so I would think that it would be ignored by this lint rule.

But the example you wrote up w/ the `Meals` component would cause a lint error.

2022-03-17 23:40 UTC, marcaaron commented
Ah thanks, I missed that it did not extend `React.Component` 😄  

So, is it just anything that calls `this` in a `constructor()` that `extends` something without calling `super()`? 
And in React components specifically `super()`must be called with `props`. 

Those are two separate things? I'm still confused why we need this and hope someone could explain it.

2022-03-18 09:30 UTC, Justicea83 commented
> ### Fixed Issues
> $[Expensify/App#7821](https://github.com/Expensify/App/issues/7821)
> 
> ### Tests
> 1. Confirm all tests still pass

@roryabraham what do you think?

2022-03-21 09:15 UTC, Justicea83 commented
Gentle bump @marcaaron

2022-03-21 19:59 UTC, marcaaron commented
Thanks @Justicea83. I am still waiting for a response to [this comment](https://github.com/Expensify/eslint-config-expensify/pull/49#issuecomment-1071845845) and then re-review. 

I still see examples like [this](https://github.com/Expensify/App/blob/36ae0cf26f66b571e08f7d9363b4ee5afad372a2/src/components/GrowlNotification/index.js#L33-L35) and I'm unsure if we care about them or not. Do we need to provide `props` to that constructor? Or not? If yes, why? Still trying to figure out whether we need this at all 😄

2022-03-21 20:37 UTC, roryabraham commented
To be honest, I don't think there's a _strong_ need for this lint issue. AFAIK the only case this rule really covers is if someone tries to access `this.props` in a class-style component without calling `super(props)` in the constructor. Incidentally, I think leaving out the constructor entirely (using the default constructor) is also valid.

Cases like [this](https://github.com/Expensify/App/blob/36ae0cf26f66b571e08f7d9363b4ee5afad372a2/src/components/GrowlNotification/index.js#L33-L35) technically are fine because the component does not access `this.props` anywhere. That said, there's no harm in including `super(props)` in the constructor, and it's probably better for consistency and in case someone adds a prop and tries to access it in the class component without adding `super(props)` in the constructor.

So overall I have no issues if we prefer to just close this, but if we _do_ want to keep it, the linter should only complain if all of the above are true:

1. A class extends `React.Component` or `Component`
1. The class has a constructor
1. The constructor does not take a props argument and call `super(props)`

All other cases should pass. Looking at the test cases @Justicea83 has included in this PR, we would just want to add a test case for a React class component that does not have a constructor at all (that should pass).

Given that @Justicea83 already put in the work and has a mostly working implementation, I personally would lean towards merging it because it will only be helpful. But I also don't think we'll sorely miss it if we decide to just close this.

2022-03-21 21:21 UTC, marcaaron commented
>That said, there's no harm in including super(props) in the constructor, and it's probably better for consistency and in case someone adds a prop and tries to access it in the class component without adding super(props) in the constructor.

I can get down with the consistency argument. I just want to make sure there is some documented understanding about why we did this.

I personally would skip it because any incorrect usage of `this` inside a constructor is already covered by the rules of JS itself and a separate lint rule

![2022-03-21_11-13-34](https://user-images.githubusercontent.com/32969087/159364918-65b2f0cf-f54a-42d7-9caa-ecb3299118ec.png)

![2022-03-21_11-20-40](https://user-images.githubusercontent.com/32969087/159365811-301622fb-d072-440b-a970-ae04e320f8a0.png)

And while there are valid cases where we could call `super()` with props passed in the constructor or without, there are only two cases where people actually called it without. So I guess that's just a long way of saying we _probably_ don't need this 😄

2022-03-28 08:59 UTC, Justicea83 commented
@marcaaron what do you suggest we do next?

2022-04-05 09:09 UTC, Justicea83 commented
gentle bump @marcaaron

2022-04-05 20:38 UTC, roryabraham commented
I'm fine with just closing this and the linked issue too. It's not a problem we've really experienced AFAIK

2022-04-06 15:00 UTC, closed without merging